### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by antoniojosesanchez** [AnderDeAbrisqueta/HarenaProjectApp#1]
- Especifica el tipo de tecnología que vas a utilizar para la base de datos (Mongo, Firebase, etc.) y la estructura de la misma.

**Comment by AnderDeAbrisqueta** [comment]
Hola Antonio, perfecto. La semana que viene escribo ese apartado.

**Comment by AnderDeAbrisqueta** [comment]
Hola Antonio, listo ya lo he completado. Me avisas si ves otra cosa. Saludos
